### ISSUE TITLE
Is there a way to handle mutations errors?

### ISSUE THREAD

**Issue by richardriman** [vendrinc/elm-gql#21]
Hi guys. I run in specific problem today. Graphql intentionally does not use HTTP error codes for errors. If there are some errors during mutation, in response field `data` is null and another key `errors` was returned in response with structured errors.

So my questing is, is there a way how to access/handle these errors? Currently I am not able to figure it out, mutation function resulting in `Ok result` every time but returning only empty result, no errors.

**Comment by mdgriffith** [comment]
I released 0.8.2 which will attempt to parse the errors field if the data is null or fails to decode in any way.

Let me know if this solves your situation or if there's something I missed!  Thanks for the issue 🙏
