### ISSUE TITLE
Generated decoder breaks if enum starts with lower case

### ISSUE THREAD

**Issue by albertdahlin** [vendrinc/elm-gql#41]
Thanks for a great tool, really enjoy working with it. Here is a problem I found when using it with Gitlab.

The `MilestoneStateEnum` values starts with lower case (`active`, `closed`) but the generated decoder expects strings to start with upper case. Manually changing the code in the decoder fixes the problem.

This is the Gitlab schema
![image](https://github.com/vendrinc/elm-gql/assets/8900986/2672323e-f0c8-4241-9955-63eb61902d88)

Generated code expects json strings `Active`, `Closed` instead of `active`, `closed`.
````graphql
decoder : Json.Decode.Decoder MilestoneStateEnum
decoder =
    Json.Decode.andThen
        (\andThenUnpack ->
            case andThenUnpack of
                "Active" ->
                    Json.Decode.succeed Active

                "Closed" ->
                    Json.Decode.succeed Closed

                _ ->
                    Json.Decode.fail "Invalid type"
        )
        Json.Decode.string
````

**Comment by mdgriffith** [comment]
0.11.3 was just released which fixes this!

Sorry for the long wait, I missed it when this issue was filed 🙏
