### ISSUE TITLE
Unknown command 'inspect'

### ISSUE THREAD

**Issue by richardriman** [vendrinc/elm-gql#6]
I'm not sure, what I'm doing wrong, but I can't get schema from introspection API, because of that error:

<code>
error: unknown command 'inspect'
</code>

Context:

I have package `elm-gql` added in devDependencies, installed using yarn, but I'm not able tu run it directly from CLI, so I running it using `npx elm-gql inspect ...`.

**Comment by richardriman** [comment]
Hah, looks like readme is not updated for current version. The initialization part is completely missing.

**Comment by alenards** [comment]
👍 The warning at the top of the README is meant to flag curious folks to beware.

**Comment by mdgriffith** [comment]
Ha, thanks!  Yeah, the commands changed but I didn't update the docs.  Now they should be updated though!
